name: Build galpy WASM

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jobovy/pyodide-buildpackage-action@cache
      with:
        package-name: galpy
        build-url: https://github.com/jobovy/galpy/archive/main.tar.gz
        pyodide-tag: 9c305efc465f033fea3aa6cccaf4fbdd93ad74f4
        build-deps: False
    - uses: actions/upload-artifact@v2-preview
      with:
        name: galpy-wheel-pyodide
        path: wheelhouse/*.whl
    - uses: actions/upload-artifact@v2-preview
      with:
        name: galpy-wheels-pyodide
        path: wheelhouse-all/*.whl
