on:
  push:
  pr:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jobovy/pyodide-buildpackage-action@firsttry
    - uses: actions/upload-artifact@v2-preview
      with:
        name: galpy-wheels-pyodide
        path: wheelhouse/*.whl
